import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime

# --- 1. 網頁設定 ---
st.set_page_config(
    page_title="Re:Jesus - 生命應用版",
    page_icon="✝️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. CSS 與 UI 優化 ---
st.markdown("""
<style>
    .prescription-card {
        background-color: #f0f7ff;
        border-left: 6px solid #0066cc;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 20px;
    }
    .quote-text {
        font-size: 1.2rem;
        font-style: italic;
        color: #555;
    }
    .big-btn {
        width: 100%;
        height: 50px;
    }
</style>
""", unsafe_allow_html=True)

# --- 3. 核心邏輯區 ---

# 定義「生命處方」的邏輯對應 (模擬 AI 判斷)
LIFE_SCENARIOS = {
    "😟 我感到焦慮/擔憂": {
        "keywords": ["平安", "不要怕", "信心", "風浪"],
        "message": "在風浪中，耶穌是那位說「住了吧」的主。你不必掌控一切，因為祂掌權。",
        "theme": "保護、信實、引導"
    },
    "😔 我覺得孤單/被遺忘": {
        "keywords": ["接納", "尋找", "痲瘋", "婦人"],
        "message": "耶穌總是主動走向那些被社會遺忘的人。在祂眼中，你是無價之寶。",
        "theme": "恩典、接納、喜樂"
    },
    "😡 我無法原諒/很生氣": {
        "keywords": ["饒恕", "愛仇敵", "憐憫", "赦免"],
        "message": "饒恕不是因為對方配得，而是因為耶穌先饒恕了我們。讓祂的愛釋放你的心。",
        "theme": "憐憫、同理、悲憫"
    },
    "😫 我覺得自己很糟糕/有罪惡感": {
        "keywords": ["呼召", "罪人", "悔改", "稅吏"],
        "message": "健康的人用不著醫生。耶穌來，正是為了像我們這樣不完美的人。",
        "theme": "恩典、主權、謙卑"
    },
    "🤔 我對信仰感到懷疑": {
        "keywords": ["多馬", "神蹟", "顯現", "真理"],
        "message": "耶穌不責備誠實的懷疑。祂願意顯現，讓你觸摸祂的真實。",
        "theme": "渴慕真理、順服、智慧"
    }
}

@st.cache_data
def load_data():
    try:
        df = pd.read_csv("data.csv")
        # 簡單的數值化日期處理 (為了畫圖)
        df['DateOrder'] = range(len(df)) 
        return df
    except FileNotFoundError:
        return None

# --- 4. 功能模組 ---

def generate_study_material(row):
    """生成小組查經教材的文字內容"""
    content = f"""
# 📖 小組查經教材：{row['事件名稱']}

## 1. 🧊 破冰 (Ice Breaker)
* 在這一週中，你有沒有遇到什麼讓你感到「{row['神學主題']}」的事情？

## 2. 🧐 觀察 (Observation)
* **經文閱讀**：{row['經文總覽']}
* **事件地點**：{row['地點']} ({row['季節']})
* **發生了什麼事**：{row['福音中心_原文'] or row['福音中心']}

## 3. 💡 解釋 (Interpretation)
* **耶穌展現了什麼品格**？
  * 參考答案：{row['耶穌品格']}
* **神學焦點**：
  * {row['福音中心_備註'] or row['福音中心']}
* **為什麼這件事對當時的人很震撼**？
  * {row['焦點']}

## 4. 🏃 應用 (Application)
* 這個事件中的耶穌，如何挑戰或是安慰你現在的生活？
* 本週你可以採取什麼具體的行動來回應這個真理？

---
*Generated by Re:Jesus Website*
"""
    return content

# --- 5. 主程式 ---
def main():
    df = load_data()
    if df is None:
        st.error("❌ 請確認 data.csv 是否存在")
        return

    # 側邊欄
    with st.sidebar:
        st.title("✝️ Re:Jesus 5.0")
        st.markdown("你的個人屬靈導航")
        menu = st.radio("功能選擇", ["💊 生命處方籤", "📅 時空軌跡圖", "📝 教材生成器", "📂 資料庫首頁"])
        st.divider()
        st.caption("Designed for everyone.")

    # === 功能 1: 生命處方籤 ===
    if menu == "💊 生命處方籤":
        st.header("💊 心靈急診室")
        st.markdown("把你現在真實的感受告訴我們，領受從耶穌而來的回應。")
        
        selected_feeling = st.selectbox("你現在感覺如何？", list(LIFE_SCENARIOS.keys()))
        
        if st.button("取得處方", type="primary"):
            scenario = LIFE_SCENARIOS[selected_feeling]
            
            # 搜尋邏輯
            mask = df.apply(lambda r: any(k in str(r['事件名稱']) or k in str(r['福音中心']) for k in scenario['keywords']), axis=1)
            results = df[mask]
            
            # 顯示處方
            st.markdown(f"""
            <div class="prescription-card">
                <h3>🩺 給你的回應：</h3>
                <p class="quote-text">{scenario['message']}</p>
                <hr>
                <p><b>推薦主題：</b>{scenario['theme']}</p>
            </div>
            """, unsafe_allow_html=True)
            
            if not results.empty:
                st.subheader(f"📖 推薦閱讀 ({len(results)} 篇)")
                for _, row in results.head(3).iterrows():
                    with st.expander(f"✨ {row['事件名稱']} ({row['經文總覽']})", expanded=True):
                        st.write(row['福音中心'])
                        st.caption(f"地點：{row['地點']}")

    # === 功能 2: 時空軌跡圖 (Timeline) ===
    elif menu == "📅 時空軌跡圖":
        st.header("📅 耶穌生平・時空軌跡")
        st.markdown("透過視覺化圖表，看見耶穌事工的節奏與張力。")
        
        # 準備圖表資料
        timeline_df = df.copy()
        # 為了讓圖表好看，我們篩選掉「後設」資料，只留事件
        timeline_df = timeline_df[~timeline_df['季節'].str.contains("後設", na=False)]
        
        # 互動式散佈圖
        chart = alt.Chart(timeline_df).mark_circle(size=100).encode(
            x=alt.X('DateOrder', title='事件發生順序 (從開始到結束)', axis=alt.Axis(labels=False)),
            y=alt.Y('地點', title='地理位置'),
            color=alt.Color('季節', legend=alt.Legend(title="時期")),
            tooltip=['事件名稱', '大約日期', '地點', '福音中心']
        ).properties(
            height=600,
            title="耶穌事工分佈圖 (顏色代表季節/最後一週)"
        ).interactive()
        
        st.altair_chart(chart, use_container_width=True)
        st.info("💡 提示：您可以使用滑鼠滾輪縮放圖表，或拖曳查看細節。")

    # === 功能 3: 教材生成器 ===
    elif menu == "📝 教材生成器":
        st.header("📝 小組長神器：一鍵生成教材")
        st.markdown("選擇一個事件，系統將自動為您編寫一份包含「破冰、觀察、解釋、應用」的完整帶領手冊。")
        
        # 選擇事件
        event_list = df['事件名稱'].tolist()
        selected_event_name = st.selectbox("請選擇今天要查考的事件：", event_list)
        
        # 抓取該行資料
        selected_row = df[df['事件名稱'] == selected_event_name].iloc[0]
        
        # 生成內容
        material_content = generate_study_material(selected_row)
        
        # 預覽區
        st.markdown("---")
        c1, c2 = st.columns([2, 1])
        with c1:
            st.markdown("### 📄 教材預覽")
            st.markdown(material_content)
        
        with c2:
            st.markdown("### 📥 下載專區")
            st.write("滿意這份教材嗎？點擊按鈕下載 Markdown 檔案，您可以直接傳給組員，或貼到 Notion/Word 編輯。")
            
            # 下載按鈕
            st.download_button(
                label="📥 下載教材 (.md)",
                data=material_content,
                file_name=f"查經教材_{selected_event_name}.md",
                mime="text/markdown"
            )

    # === 功能 4: 資料庫首頁 (保留基本查詢) ===
    elif menu == "📂 資料庫首頁":
        st.title("📂 耶穌生平資料庫")
        search = st.text_input("快速搜尋", placeholder="輸入關鍵字...")
        
        show_df = df.copy()
        if search:
            show_df = show_df[show_df.astype(str).apply(lambda x: x.str.contains(search, case=False)).any(axis=1)]
            
        st.dataframe(
            show_df[['事件名稱', '季節', '地點', '經文總覽', '福音中心']],
            hide_index=True,
            use_container_width=True
        )

if __name__ == "__main__":
    main()
